<?php 

$servername = "localhost";
$username = "root";
$password = "admin";
$dbname = "alpbits";
// Create connection
$connection = new mysqli($servername, $username, $password ,$dbname);

$sql = "SELECT * FROM country";
$result = mysqli_query($connection,$sql);

?>
<!DOCTYPE html>
<html class="no-js" lang="en-US">
   <head>
      <title>AlpBits</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" >
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0">
      <link rel="stylesheet" type="text/css" href="css/jquery.mmenu.all.css"/>
      <link rel="stylesheet" type="text/css" href="css/owl.carousel.min.css">
      <link rel="stylesheet" type="text/css" href="css/style.css">
      <script type="text/javascript" src="js/jquery.min.js"></script>
      <script type="text/javascript" src="js/owl.carousel.min.js"></script>
      <script type="text/javascript" src="js/jquery.mmenu.min.all.js"></script>
      <script type="text/javascript" src="js/custom.js"></script>
   </head>
   <body>
      <div id="page">
         <header class="header">
            <div class="container">
               <div class="logo">
                  <a href="javascript:void(0)">
                  AlpBits
                  </a>
               </div>
               <div class="navigation">
                  <nav>
                     <ul>
                        <li><a href="javascript:void(0)">Home</a></li>
                        <li><a href="javascript:void(0)">Services</a></li>
                        <li><a href="javascript:void(0)">About Us</a></li>
                        <li><a href="javascript:void(0)">Contact Us</a></li>
                     </ul>
                  </nav>
                  <div class="responsive_nav">
                     <div class="mh-head ">
                        <span>
                           <a href="#menu" class="menu_icon">
                              <svg xmlns="http://www.w3.org/2000/svg" fill="#fff" viewBox="0 0 24 24" width="42px" height="28px">
                                 <path d="M 0 2 L 0 4 L 24 4 L 24 2 Z M 0 11 L 0 13 L 24 13 L 24 11 Z M 0 20 L 0 22 L 24 22 L 24 20 Z"/>
                              </svg>
                           </a>
                        </span>
                     </div>
                  </div>
               </div>
            </div>
         </header>
         <section class="banner_section">
            <ul id="banner" class="home_banner owl-carousel">
               <li>
                  <img src="images/banner_1.jpg" title="" alt=""/>
               </li>
               <li>
                  <img src="images/banner_2.jpg" title="" alt=""/>
               </li>
               <li>
                  <img src="images/banner_3.jpg" title="" alt=""/>
               </li>
            </ul>
         </section>
         <section class="our_section">
            <div class="container">
               <h1 class="border-bottom"><span>Our Services</span></h1>
               <div class="services">
                  <ul>
                     <li>
                        <a href="javascript:void(0)">
                           <div class="srv_img">
                              <figure>
                                 <img src="images/our_1.jpeg" alt="" title=""/>
                              </figure>
                           </div>
                           <h2><span>Embedded</span></h2>
                        </a>
                     </li>
                     <li>
                        <a href="javascript:void(0)">
                           <div class="srv_img">
                              <figure>
                                 <img src="images/our_2.jpeg" alt="" title=""/>
                              </figure>
                           </div>
                           <h2><span>Automation</span></h2>
                        </a>
                     </li>
                     <li>
                        <a href="javascript:void(0)">
                           <div class="srv_img">
                              <figure>
                                 <img src="images/our_3.jpeg" alt="" title=""/>
                              </figure>
                           </div>
                           <h2><span>Web Design</span></h2>
                        </a>
                     </li>
                  </ul>
               </div>
            </div>
         </section>
         <section class="expertise_section">
            <div class="container">
               <h3 class="border-bottom white-border"><span>Expertise</span></h3>
               <div class="exp_sec">
                  <ul>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/icons8-c-programming-144.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/c-plus-plus-logo.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">	  						
                        <img src="images/python.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/magento.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/database.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/mysql_logo.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/git.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/new-php-logo.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/linux.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/raspberry_pi.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/embedded.png">
                        </a>
                     </li>
                     <li>
                        <a class="" href="javascript:void(0)">
                        <img src="images/arduino.png">
                        </a>
                     </li>
                  </ul>
               </div>
            </div>
         </section>
         <section class="about_section">
            <div class="container">
               <h4 class="border-bottom"><span>About US</span></h4>
               <div class="about-contand">
                  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                  <p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                  <a href="#">Learn More +</a>
               </div>
            </div>
         </section>
         <section class="contact_section">
            <div class="container">
               <h5 class="border-bottom white-border"><span>Contact US</span></h5>
               <p class="error_message"></p>
               <div class="overlay"></div>
               <form method="POST" id="contactform">
                  <div class="left-box">
                     <div class="form-group">
                        <input type="text" placeholder="Enter Name" id="name" name="name" autocomplete="off" class="form-control">
                     </div>
                     <div class="form-group">
                        <input type="text" placeholder="Enter Email" id="email" name="email" autocomplete="off" class="form-control">
                     </div>
                     <div class="form-group">
                        <input type="tel" placeholder="Enter Number" name="mobile" id="mobile" autocomplete="off" maxlength="10" class="form-control">
                     </div>
                     <div class="form-group">
                        <select name="countryCode" id="country"  class="form-control">
                           <option value="none" selected disabled>-- Select Country --</option>
                           <?php 
                           		while ($row = mysqli_fetch_array($result)){ 
									?><option value="<?php echo $row['iso'];?>" ><?php echo $row['name']; ?></option><?php
								}
                           ?>
                        </select>
                     </div>
                  </div>
                  <div class="right-box">
                     <div class="form-group">
                        <textarea class="form-control" placeholder="Drop your message here" id="comment" name="comment"></textarea>
                     </div>
                  </div>
                  <button type="button" id="btn_submit" class="btn btn-primary submit">Submit</button>
               </form>
            </div>
         </section>
         <footer>
            <div class="container">
               <div class="logo">
                  All rights reserved by <a href="#">AlpBits</a> © 2020
               </div>
            </div>
         </footer>
      </div>
      <nav id="menu" class="mobile_menu">
         <a href="#page" class="close_icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="#fff" viewBox="0 0 50 50" width="18px" height="18px">
               <path d="M 9.15625 6.3125 L 6.3125 9.15625 L 22.15625 25 L 6.21875 40.96875 L 9.03125 43.78125 L 25 27.84375 L 40.9375 43.78125 L 43.78125 40.9375 L 27.84375 25 L 43.6875 9.15625 L 40.84375 6.3125 L 25 22.15625 Z"/>
            </svg>
         </a>
         <ul>
            <li><a href="javascript:void(0)">Home</a></li>
            <li><a href="javascript:void(0)">Services</a></li>
            <li><a href="javascript:void(0)">About Us</a></li>
            <li><a href="javascript:void(0)">Contact Us</a></li>
         </ul>
      </nav>
      
      
      <script>jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>140){jQuery('.header').addClass("sticky");}
         else{jQuery('.header').removeClass("sticky");}});
      </script>
      <script type="text/javascript">
         $('.home_banner').owlCarousel({
            loop:true,
            margin:0,
            dots: true,
            nav: true,
            autoplay:true,
            smartSpeed: 3000,
            items:1       
         });
      </script>
      <script type="text/javascript">     
         $( document ).ready(function() {
               //Mmenu JS     
             $('nav#menu').mmenu({
	             "extensions": [
	                   "fx-menu-zoom",
	                   "pagedim-black"
	                ],               
	             navbars:[ {
	                 position: 'top',
	                 content: ['prev', 'title', 'close']
	             }
	             ]           
             });
        });
      </script>
   </body>
</html>
<style>
.overlay{
    display: none;
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 999;
    background: rgba(255,255,255,0.8) url("images/35.gif") center no-repeat;
}
/* Turn off scrollbar when body element has the loading class */
body.loading{
    overflow: hidden;   
}
/* Make spinner image visible when body element has the loading class */
body.loading .overlay{
    display: block;
}
</style>